(function() {

  window.Arena = (function() {

    function Arena(w, h, players) {
      var background, shape;
      this.w = w;
      this.h = h;
      this.players = players != null ? players : {};
      this.container = new createjs.Container();
      this.container.x = 0;
      this.container.y = 0;
      background = new createjs.Graphics().beginFill("#FFFFFE").drawRect(0, 0, this.w, this.h);
      shape = new createjs.Shape(background);
      shape.x = 0;
      shape.y = 0;
      this.container.addChild(shape);
      this.init();
    }

    Arena.prototype.init = function() {
      var p, _i, _len, _ref, _results;
      _ref = this.players;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        p = _ref[_i];
        console.log('add');
        _results.push(this.container.addChild(p.getPlayer()));
      }
      return _results;
    };

    Arena.prototype.setPosition = function(x, y) {
      this.container.x = x;
      return this.container.y = y;
    };

    Arena.prototype.addPlayer = function(player) {
      this.container.addChild(player.getPlayer());
      return this.players.push(player);
    };

    Arena.prototype.addToStage = function(stage) {
      return stage.addChild(this.container);
    };

    Arena.prototype.getPlayers = function() {
      return this.players;
    };

    return Arena;

  })();

}).call(this);

// Generated by CoffeeScript 1.5.0-pre
