(function() {

  window.Constant = {
    KEYCODE_ENTER: 13,
    KEYCODE_SPACE: 32,
    KEYCODE_UP: 38,
    KEYCODE_LEFT: 37,
    KEYCODE_RIGHT: 39,
    KEYCODE_W: 87,
    KEYCODE_A: 65,
    KEYCODE_D: 68,
    KEYCODE_Z: 90,
    KEYCODE_DOWN: 40
  };

}).call(this);

// Generated by CoffeeScript 1.5.0-pre
