// Generated by CoffeeScript 1.6.1
(function() {

  window.Hud = (function() {

    function Hud(players, w, h, stage) {
      var background, g, s;
      this.players = players;
      this.w = w;
      this.h = h;
      this.stage = stage;
      this.container = new createjs.Container();
      this.container.x = 0;
      this.container.y = 0;
      background = new createjs.Graphics().beginFill("#3D414C").drawRect(0, 0, this.w, this.h);
      this.shape = new createjs.Shape(background);
      this.shape.x = 0;
      this.shape.y = 0;
      g = new createjs.Graphics();
      g.setStrokeStyle(1);
      g.beginStroke(createjs.Graphics.getRGB(0, 0, 0));
      g.beginFill(createjs.Graphics.getRGB(255, 0, 0));
      g.drawRoundRect(0, 0, 30, 30, 3);
      s = new createjs.Shape(g);
      s.x = 100;
      s.y = 100;
      this.init();
    }

    Hud.prototype.init = function() {
      this.container.addChild(this.shape);
      return this.stage.addChild(this.container);
    };

    return Hud;

  })();

}).call(this);
