// Generated by CoffeeScript 1.6.1
  var Character;

  Character = (function() {

    function Character(id, x, y) {
      this.id = id
      this.speed = speed;
      this.x = x;
      this.y = y;
      this.stage = stage;
      this.hp = 100;
      this.spriteSheetInfo;
      this.character;
      this.characterSpriteSheet;
      this.direction = "right";
      this.stage;
      this.state = "idle";
      this.init();
    }


    return Character;

  });


 exports.Character = Character;

